apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  custom:
    delegates: rajnish-cloudbees/test-integration/.cloudbees/custom.yaml
    with:
      param1: "testing param"
    timeout-minutes: 30

  build:
    needs: custom
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world ${{ needs.custom.outputs.result }}"
